; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30137.0 

include listing.inc




CONST	SEGMENT
$SG2838	DB	'48 89 ? ? ? 56 48 81 EC ? ? ? ? 48 8B ? ? ? ? ? 48 33 ? '
	DB	'48 89 ? ? ? ? ? ? 83 79 04', 00H
CONST	ENDS
PUBLIC	main
PUBLIC	shellMain
; Function compile flags: /Odtp
_TEXT	SEGMENT
name$ = 32
FNameToString$ = 40
ret$ = 48
data$ = 80
shellMain PROC
; File E:\source\repos\FNameToStringEx\ShellcodeTool\cpp\c-shellcode.cpp
; Line 10
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 12
	mov	rax, QWORD PTR data$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR name$[rsp], eax
	mov	DWORD PTR name$[rsp+4], 0
; Line 14
	mov	rax, 230699098558929			; 0000d1d1d1d1d1d1H
	mov	QWORD PTR FNameToString$[rsp], rax
; Line 15
	lea	rdx, QWORD PTR ret$[rsp]
	lea	rcx, QWORD PTR name$[rsp]
	call	QWORD PTR FNameToString$[rsp]
; Line 17
	mov	rax, QWORD PTR data$[rsp]
	mov	rcx, QWORD PTR ret$[rsp]
	mov	QWORD PTR [rax+8], rcx
; Line 18
	add	rsp, 72					; 00000048H
	ret	0
shellMain ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File E:\source\repos\FNameToStringEx\ShellcodeTool\cpp\c-shellcode.cpp
; Line 6
	xor	eax, eax
; Line 7
	ret	0
main	ENDP
_TEXT	ENDS
END
