; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30137.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?get_module_by_name@@YAPEAXPEA_W@Z		; get_module_by_name
PUBLIC	?get_func_by_name@@YAPEAXPEAXPEAD@Z		; get_func_by_name
PUBLIC	main
PUBLIC	maindeez
;	COMDAT pdata
pdata	SEGMENT
$pdata$?get_module_by_name@@YAPEAXPEA_W@Z DD imagerel $LN16
	DD	imagerel $LN16+567
	DD	imagerel $unwind$?get_module_by_name@@YAPEAXPEA_W@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?get_func_by_name@@YAPEAXPEAXPEAD@Z DD imagerel $LN13
	DD	imagerel $LN13+568
	DD	imagerel $unwind$?get_func_by_name@@YAPEAXPEAXPEAD@Z
pdata	ENDS
pdata	SEGMENT
$pdata$maindeez DD imagerel $LN7
	DD	imagerel $LN7+947
	DD	imagerel $unwind$maindeez
pdata	ENDS
xdata	SEGMENT
$unwind$maindeez DD 020b01H
	DD	023010bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?get_func_by_name@@YAPEAXPEAXPEAD@Z DD 010e01H
	DD	0e20eH
xdata	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	014H
voltbl	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?get_module_by_name@@YAPEAXPEA_W@Z DD 030b01H
	DD	07007c20bH
	DD	06006H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
user32_dll_name$ = 32
message_box_name$ = 48
load_lib_name$ = 64
get_proc_name$ = 80
msg_title$ = 96
kernel32_dll_name$ = 112
base$ = 144
msg_content$ = 152
load_lib$ = 184
get_proc$ = 192
test$ = 200
_MessageBoxW$ = 208
_LoadLibraryA$ = 216
u32_dll$ = 224
_GetProcAddress$ = 232
FNameToString$ = 240
temp$ = 248
index$ = 288
maindeez PROC
; File E:\source\repos\ShellcodeTool\cpp\c-shellcode.cpp
; Line 27
$LN7:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 280				; 00000118H
; Line 29
	mov	eax, 107				; 0000006bH
	mov	WORD PTR kernel32_dll_name$[rsp], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR kernel32_dll_name$[rsp+2], ax
	mov	eax, 114				; 00000072H
	mov	WORD PTR kernel32_dll_name$[rsp+4], ax
	mov	eax, 110				; 0000006eH
	mov	WORD PTR kernel32_dll_name$[rsp+6], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR kernel32_dll_name$[rsp+8], ax
	mov	eax, 108				; 0000006cH
	mov	WORD PTR kernel32_dll_name$[rsp+10], ax
	mov	eax, 51					; 00000033H
	mov	WORD PTR kernel32_dll_name$[rsp+12], ax
	mov	eax, 50					; 00000032H
	mov	WORD PTR kernel32_dll_name$[rsp+14], ax
	mov	eax, 46					; 0000002eH
	mov	WORD PTR kernel32_dll_name$[rsp+16], ax
	mov	eax, 100				; 00000064H
	mov	WORD PTR kernel32_dll_name$[rsp+18], ax
	mov	eax, 108				; 0000006cH
	mov	WORD PTR kernel32_dll_name$[rsp+20], ax
	mov	eax, 108				; 0000006cH
	mov	WORD PTR kernel32_dll_name$[rsp+22], ax
	xor	eax, eax
	mov	WORD PTR kernel32_dll_name$[rsp+24], ax
; Line 30
	mov	BYTE PTR load_lib_name$[rsp], 76	; 0000004cH
	mov	BYTE PTR load_lib_name$[rsp+1], 111	; 0000006fH
	mov	BYTE PTR load_lib_name$[rsp+2], 97	; 00000061H
	mov	BYTE PTR load_lib_name$[rsp+3], 100	; 00000064H
	mov	BYTE PTR load_lib_name$[rsp+4], 76	; 0000004cH
	mov	BYTE PTR load_lib_name$[rsp+5], 105	; 00000069H
	mov	BYTE PTR load_lib_name$[rsp+6], 98	; 00000062H
	mov	BYTE PTR load_lib_name$[rsp+7], 114	; 00000072H
	mov	BYTE PTR load_lib_name$[rsp+8], 97	; 00000061H
	mov	BYTE PTR load_lib_name$[rsp+9], 114	; 00000072H
	mov	BYTE PTR load_lib_name$[rsp+10], 121	; 00000079H
	mov	BYTE PTR load_lib_name$[rsp+11], 65	; 00000041H
	mov	BYTE PTR load_lib_name$[rsp+12], 0
; Line 31
	mov	BYTE PTR get_proc_name$[rsp], 71	; 00000047H
	mov	BYTE PTR get_proc_name$[rsp+1], 101	; 00000065H
	mov	BYTE PTR get_proc_name$[rsp+2], 116	; 00000074H
	mov	BYTE PTR get_proc_name$[rsp+3], 80	; 00000050H
	mov	BYTE PTR get_proc_name$[rsp+4], 114	; 00000072H
	mov	BYTE PTR get_proc_name$[rsp+5], 111	; 0000006fH
	mov	BYTE PTR get_proc_name$[rsp+6], 99	; 00000063H
	mov	BYTE PTR get_proc_name$[rsp+7], 65	; 00000041H
	mov	BYTE PTR get_proc_name$[rsp+8], 100	; 00000064H
	mov	BYTE PTR get_proc_name$[rsp+9], 100	; 00000064H
	mov	BYTE PTR get_proc_name$[rsp+10], 114	; 00000072H
	mov	BYTE PTR get_proc_name$[rsp+11], 101	; 00000065H
	mov	BYTE PTR get_proc_name$[rsp+12], 115	; 00000073H
	mov	BYTE PTR get_proc_name$[rsp+13], 115	; 00000073H
	mov	BYTE PTR get_proc_name$[rsp+14], 0
; Line 32
	mov	BYTE PTR user32_dll_name$[rsp], 117	; 00000075H
	mov	BYTE PTR user32_dll_name$[rsp+1], 115	; 00000073H
	mov	BYTE PTR user32_dll_name$[rsp+2], 101	; 00000065H
	mov	BYTE PTR user32_dll_name$[rsp+3], 114	; 00000072H
	mov	BYTE PTR user32_dll_name$[rsp+4], 51	; 00000033H
	mov	BYTE PTR user32_dll_name$[rsp+5], 50	; 00000032H
	mov	BYTE PTR user32_dll_name$[rsp+6], 46	; 0000002eH
	mov	BYTE PTR user32_dll_name$[rsp+7], 100	; 00000064H
	mov	BYTE PTR user32_dll_name$[rsp+8], 108	; 0000006cH
	mov	BYTE PTR user32_dll_name$[rsp+9], 108	; 0000006cH
	mov	BYTE PTR user32_dll_name$[rsp+10], 0
; Line 33
	mov	BYTE PTR message_box_name$[rsp], 77	; 0000004dH
	mov	BYTE PTR message_box_name$[rsp+1], 101	; 00000065H
	mov	BYTE PTR message_box_name$[rsp+2], 115	; 00000073H
	mov	BYTE PTR message_box_name$[rsp+3], 115	; 00000073H
	mov	BYTE PTR message_box_name$[rsp+4], 97	; 00000061H
	mov	BYTE PTR message_box_name$[rsp+5], 103	; 00000067H
	mov	BYTE PTR message_box_name$[rsp+6], 101	; 00000065H
	mov	BYTE PTR message_box_name$[rsp+7], 66	; 00000042H
	mov	BYTE PTR message_box_name$[rsp+8], 111	; 0000006fH
	mov	BYTE PTR message_box_name$[rsp+9], 120	; 00000078H
	mov	BYTE PTR message_box_name$[rsp+10], 87	; 00000057H
	mov	BYTE PTR message_box_name$[rsp+11], 0
; Line 36
	mov	eax, 72					; 00000048H
	mov	WORD PTR msg_content$[rsp], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR msg_content$[rsp+2], ax
	mov	eax, 108				; 0000006cH
	mov	WORD PTR msg_content$[rsp+4], ax
	mov	eax, 108				; 0000006cH
	mov	WORD PTR msg_content$[rsp+6], ax
	mov	eax, 111				; 0000006fH
	mov	WORD PTR msg_content$[rsp+8], ax
	mov	eax, 32					; 00000020H
	mov	WORD PTR msg_content$[rsp+10], ax
	mov	eax, 87					; 00000057H
	mov	WORD PTR msg_content$[rsp+12], ax
	mov	eax, 111				; 0000006fH
	mov	WORD PTR msg_content$[rsp+14], ax
	mov	eax, 114				; 00000072H
	mov	WORD PTR msg_content$[rsp+16], ax
	mov	eax, 108				; 0000006cH
	mov	WORD PTR msg_content$[rsp+18], ax
	mov	eax, 100				; 00000064H
	mov	WORD PTR msg_content$[rsp+20], ax
	mov	eax, 33					; 00000021H
	mov	WORD PTR msg_content$[rsp+22], ax
	xor	eax, eax
	mov	WORD PTR msg_content$[rsp+24], ax
; Line 37
	mov	eax, 75					; 0000004bH
	mov	WORD PTR msg_title$[rsp], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR msg_title$[rsp+2], ax
	mov	eax, 109				; 0000006dH
	mov	WORD PTR msg_title$[rsp+4], ax
	mov	eax, 111				; 0000006fH
	mov	WORD PTR msg_title$[rsp+6], ax
	xor	eax, eax
	mov	WORD PTR msg_title$[rsp+8], ax
; Line 40
	lea	rcx, QWORD PTR kernel32_dll_name$[rsp]
	call	?get_module_by_name@@YAPEAXPEA_W@Z	; get_module_by_name
	mov	QWORD PTR base$[rsp], rax
; Line 41
	cmp	QWORD PTR base$[rsp], 0
	jne	SHORT $LN2@maindeez
; Line 43
	xor	eax, eax
	jmp	$LN1@maindeez
$LN2@maindeez:
; Line 47
	lea	rdx, QWORD PTR load_lib_name$[rsp]
	mov	rcx, QWORD PTR base$[rsp]
	call	?get_func_by_name@@YAPEAXPEAXPEAD@Z	; get_func_by_name
	mov	QWORD PTR load_lib$[rsp], rax
; Line 48
	cmp	QWORD PTR load_lib$[rsp], 0
	jne	SHORT $LN3@maindeez
; Line 50
	xor	eax, eax
	jmp	$LN1@maindeez
$LN3@maindeez:
; Line 54
	lea	rdx, QWORD PTR get_proc_name$[rsp]
	mov	rcx, QWORD PTR base$[rsp]
	call	?get_func_by_name@@YAPEAXPEAXPEAD@Z	; get_func_by_name
	mov	QWORD PTR get_proc$[rsp], rax
; Line 55
	cmp	QWORD PTR get_proc$[rsp], 0
	jne	SHORT $LN4@maindeez
; Line 57
	xor	eax, eax
	jmp	$LN1@maindeez
$LN4@maindeez:
; Line 62
	mov	rax, QWORD PTR load_lib$[rsp]
	mov	QWORD PTR _LoadLibraryA$[rsp], rax
; Line 65
	mov	rax, QWORD PTR get_proc$[rsp]
	mov	QWORD PTR _GetProcAddress$[rsp], rax
; Line 69
	lea	rcx, QWORD PTR user32_dll_name$[rsp]
	call	QWORD PTR _LoadLibraryA$[rsp]
	mov	QWORD PTR u32_dll$[rsp], rax
; Line 72
	lea	rdx, QWORD PTR message_box_name$[rsp]
	mov	rcx, QWORD PTR u32_dll$[rsp]
	call	QWORD PTR _GetProcAddress$[rsp]
	mov	QWORD PTR _MessageBoxW$[rsp], rax
; Line 75
	cmp	QWORD PTR _MessageBoxW$[rsp], 0
	jne	SHORT $LN5@maindeez
; Line 76
	xor	eax, eax
	jmp	SHORT $LN1@maindeez
$LN5@maindeez:
; Line 79
	mov	eax, DWORD PTR index$[rsp]
	mov	DWORD PTR test$[rsp], eax
	mov	DWORD PTR test$[rsp+4], 0
; Line 80
	mov	rax, 230699098558929			; 0000d1d1d1d1d1d1H
	mov	QWORD PTR FNameToString$[rsp], rax
; Line 81
	lea	rdx, QWORD PTR temp$[rsp]
	lea	rcx, QWORD PTR test$[rsp]
	call	QWORD PTR FNameToString$[rsp]
; Line 84
	xor	r9d, r9d
	lea	r8, QWORD PTR msg_title$[rsp]
	mov	rdx, QWORD PTR temp$[rsp]
	xor	ecx, ecx
	call	QWORD PTR _MessageBoxW$[rsp]
; Line 86
	mov	rax, QWORD PTR temp$[rsp]
$LN1@maindeez:
; Line 87
	add	rsp, 280				; 00000118H
	ret	0
maindeez ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File E:\source\repos\ShellcodeTool\cpp\c-shellcode.cpp
; Line 23
	xor	eax, eax
; Line 24
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_func_by_name@@YAPEAXPEAXPEAD@Z
_TEXT	SEGMENT
k$1 = 0
i$2 = 8
exp$ = 16
expAddr$ = 24
funcNamesListRVA$ = 28
namesOrdsListRVA$ = 32
funcsListRVA$ = 36
curr_name$3 = 40
idh$ = 48
exportsDir$ = 56
nt_headers$ = 64
namesCount$ = 72
nameIndex$4 = 80
nameRVA$5 = 88
funcRVA$6 = 96
module$ = 128
func_name$ = 136
?get_func_by_name@@YAPEAXPEAXPEAD@Z PROC		; get_func_by_name, COMDAT
; File E:\source\repos\ShellcodeTool\cpp\peb-lookup.h
; Line 109
$LN13:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 120				; 00000078H
; Line 110
	mov	rax, QWORD PTR module$[rsp]
	mov	QWORD PTR idh$[rsp], rax
; Line 111
	mov	rax, QWORD PTR idh$[rsp]
	movzx	eax, WORD PTR [rax]
	cmp	eax, 23117				; 00005a4dH
	je	SHORT $LN8@get_func_b
; Line 113
	xor	eax, eax
	jmp	$LN1@get_func_b
$LN8@get_func_b:
; Line 115
	mov	rax, QWORD PTR idh$[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR module$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR nt_headers$[rsp], rax
; Line 116
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR nt_headers$[rsp]
	lea	rax, QWORD PTR [rcx+rax+136]
	mov	QWORD PTR exportsDir$[rsp], rax
; Line 117
	mov	rax, QWORD PTR exportsDir$[rsp]
	cmp	DWORD PTR [rax], 0
	jne	SHORT $LN9@get_func_b
; Line 119
	xor	eax, eax
	jmp	$LN1@get_func_b
$LN9@get_func_b:
; Line 122
	mov	rax, QWORD PTR exportsDir$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR expAddr$[rsp], eax
; Line 123
	mov	eax, DWORD PTR expAddr$[rsp]
	add	rax, QWORD PTR module$[rsp]
	mov	QWORD PTR exp$[rsp], rax
; Line 124
	mov	rax, QWORD PTR exp$[rsp]
	mov	eax, DWORD PTR [rax+24]
	mov	QWORD PTR namesCount$[rsp], rax
; Line 126
	mov	rax, QWORD PTR exp$[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	DWORD PTR funcsListRVA$[rsp], eax
; Line 127
	mov	rax, QWORD PTR exp$[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	DWORD PTR funcNamesListRVA$[rsp], eax
; Line 128
	mov	rax, QWORD PTR exp$[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	DWORD PTR namesOrdsListRVA$[rsp], eax
; Line 131
	mov	QWORD PTR i$2[rsp], 0
	jmp	SHORT $LN4@get_func_b
$LN2@get_func_b:
	mov	rax, QWORD PTR i$2[rsp]
	inc	rax
	mov	QWORD PTR i$2[rsp], rax
$LN4@get_func_b:
	mov	rax, QWORD PTR namesCount$[rsp]
	cmp	QWORD PTR i$2[rsp], rax
	jae	$LN3@get_func_b
; Line 133
	mov	eax, DWORD PTR funcNamesListRVA$[rsp]
	mov	rcx, QWORD PTR module$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR i$2[rsp]
	lea	rax, QWORD PTR [rax+rcx*4]
	mov	QWORD PTR nameRVA$5[rsp], rax
; Line 134
	mov	eax, DWORD PTR namesOrdsListRVA$[rsp]
	mov	rcx, QWORD PTR module$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR i$2[rsp]
	lea	rax, QWORD PTR [rax+rcx*2]
	mov	QWORD PTR nameIndex$4[rsp], rax
; Line 135
	mov	eax, DWORD PTR funcsListRVA$[rsp]
	mov	rcx, QWORD PTR module$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR nameIndex$4[rsp]
	movzx	ecx, WORD PTR [rcx]
	lea	rax, QWORD PTR [rax+rcx*4]
	mov	QWORD PTR funcRVA$6[rsp], rax
; Line 137
	mov	rax, QWORD PTR nameRVA$5[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR module$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR curr_name$3[rsp], rax
; Line 138
	mov	QWORD PTR k$1[rsp], 0
; Line 139
	mov	QWORD PTR k$1[rsp], 0
	jmp	SHORT $LN7@get_func_b
$LN5@get_func_b:
	mov	rax, QWORD PTR k$1[rsp]
	inc	rax
	mov	QWORD PTR k$1[rsp], rax
$LN7@get_func_b:
	mov	rax, QWORD PTR k$1[rsp]
	mov	rcx, QWORD PTR func_name$[rsp]
	add	rcx, rax
	mov	rax, rcx
	movsx	eax, BYTE PTR [rax]
	test	eax, eax
	je	SHORT $LN6@get_func_b
	mov	rax, QWORD PTR k$1[rsp]
	mov	rcx, QWORD PTR curr_name$3[rsp]
	add	rcx, rax
	mov	rax, rcx
	movsx	eax, BYTE PTR [rax]
	test	eax, eax
	je	SHORT $LN6@get_func_b
; Line 141
	mov	rax, QWORD PTR k$1[rsp]
	mov	rcx, QWORD PTR func_name$[rsp]
	add	rcx, rax
	mov	rax, rcx
	movsx	eax, BYTE PTR [rax]
	mov	rcx, QWORD PTR k$1[rsp]
	mov	rdx, QWORD PTR curr_name$3[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	movsx	ecx, BYTE PTR [rcx]
	cmp	eax, ecx
	je	SHORT $LN10@get_func_b
; Line 142
	jmp	SHORT $LN6@get_func_b
$LN10@get_func_b:
; Line 143
	jmp	SHORT $LN5@get_func_b
$LN6@get_func_b:
; Line 144
	mov	rax, QWORD PTR k$1[rsp]
	mov	rcx, QWORD PTR func_name$[rsp]
	add	rcx, rax
	mov	rax, rcx
	movsx	eax, BYTE PTR [rax]
	test	eax, eax
	jne	SHORT $LN11@get_func_b
	mov	rax, QWORD PTR k$1[rsp]
	mov	rcx, QWORD PTR curr_name$3[rsp]
	add	rcx, rax
	mov	rax, rcx
	movsx	eax, BYTE PTR [rax]
	test	eax, eax
	jne	SHORT $LN11@get_func_b
; Line 147
	mov	rax, QWORD PTR funcRVA$6[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR module$[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@get_func_b
$LN11@get_func_b:
; Line 149
	jmp	$LN2@get_func_b
$LN3@get_func_b:
; Line 150
	xor	eax, eax
$LN1@get_func_b:
; Line 151
	add	rsp, 120				; 00000078H
	ret	0
?get_func_by_name@@YAPEAXPEAXPEAD@Z ENDP		; get_func_by_name
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_module_by_name@@YAPEAXPEA_W@Z
_TEXT	SEGMENT
i$1 = 0
tv136 = 8
tv155 = 10
c1$2 = 12
c2$3 = 16
curr_name$4 = 24
curr_module$ = 32
tv132 = 40
tv151 = 44
peb$ = 48
ldr$ = 56
Flink$ = 64
list$ = 72
module_name$ = 128
?get_module_by_name@@YAPEAXPEA_W@Z PROC			; get_module_by_name, COMDAT
; File E:\source\repos\ShellcodeTool\cpp\peb-lookup.h
; Line 69
$LN16:
	mov	QWORD PTR [rsp+8], rcx
	push	rsi
	push	rdi
	sub	rsp, 104				; 00000068H
; Line 70
	mov	QWORD PTR peb$[rsp], 0
; Line 72
	mov	rax, QWORD PTR gs:96
	mov	QWORD PTR peb$[rsp], rax
; Line 76
	mov	rax, QWORD PTR peb$[rsp]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR ldr$[rsp], rax
; Line 77
	lea	rax, QWORD PTR list$[rsp]
	mov	rcx, QWORD PTR ldr$[rsp]
	mov	rdi, rax
	lea	rsi, QWORD PTR [rcx+16]
	mov	ecx, 16
	rep movsb
; Line 79
	mov	rax, QWORD PTR list$[rsp]
	mov	QWORD PTR Flink$[rsp], rax
; Line 80
	mov	rax, QWORD PTR Flink$[rsp]
	mov	QWORD PTR curr_module$[rsp], rax
$LN15@get_module:
$LN2@get_module:
; Line 82
	cmp	QWORD PTR curr_module$[rsp], 0
	je	$LN3@get_module
	mov	rax, QWORD PTR curr_module$[rsp]
	cmp	QWORD PTR [rax+48], 0
	je	$LN3@get_module
; Line 84
	mov	rax, QWORD PTR curr_module$[rsp]
	cmp	QWORD PTR [rax+96], 0
	jne	SHORT $LN7@get_module
; Line 85
	jmp	SHORT $LN2@get_module
$LN7@get_module:
; Line 86
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax+96]
	mov	QWORD PTR curr_name$4[rsp], rax
; Line 88
	mov	QWORD PTR i$1[rsp], 0
; Line 89
	mov	QWORD PTR i$1[rsp], 0
	jmp	SHORT $LN6@get_module
$LN4@get_module:
	mov	rax, QWORD PTR i$1[rsp]
	inc	rax
	mov	QWORD PTR i$1[rsp], rax
$LN6@get_module:
	mov	rax, QWORD PTR module_name$[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	test	eax, eax
	je	$LN5@get_module
	mov	rax, QWORD PTR curr_name$4[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	test	eax, eax
	je	$LN5@get_module
; Line 92
	mov	rax, QWORD PTR module_name$[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	cmp	eax, 90					; 0000005aH
	jg	SHORT $LN11@get_module
	mov	rax, QWORD PTR module_name$[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	cmp	eax, 65					; 00000041H
	jl	SHORT $LN11@get_module
	mov	rax, QWORD PTR module_name$[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	sub	eax, 65					; 00000041H
	add	eax, 97					; 00000061H
	mov	DWORD PTR tv132[rsp], eax
	mov	rax, QWORD PTR module_name$[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	edx, WORD PTR tv132[rsp]
	mov	WORD PTR [rax+rcx*2], dx
	movzx	eax, WORD PTR tv132[rsp]
	mov	WORD PTR tv136[rsp], ax
	jmp	SHORT $LN12@get_module
$LN11@get_module:
	mov	rax, QWORD PTR module_name$[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	mov	WORD PTR tv136[rsp], ax
$LN12@get_module:
	movzx	eax, WORD PTR tv136[rsp]
	mov	WORD PTR c1$2[rsp], ax
; Line 93
	mov	rax, QWORD PTR curr_name$4[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	cmp	eax, 90					; 0000005aH
	jg	SHORT $LN13@get_module
	mov	rax, QWORD PTR curr_name$4[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	cmp	eax, 65					; 00000041H
	jl	SHORT $LN13@get_module
	mov	rax, QWORD PTR curr_name$4[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	sub	eax, 65					; 00000041H
	add	eax, 97					; 00000061H
	mov	DWORD PTR tv151[rsp], eax
	mov	rax, QWORD PTR curr_name$4[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	edx, WORD PTR tv151[rsp]
	mov	WORD PTR [rax+rcx*2], dx
	movzx	eax, WORD PTR tv151[rsp]
	mov	WORD PTR tv155[rsp], ax
	jmp	SHORT $LN14@get_module
$LN13@get_module:
	mov	rax, QWORD PTR curr_name$4[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	mov	WORD PTR tv155[rsp], ax
$LN14@get_module:
	movzx	eax, WORD PTR tv155[rsp]
	mov	WORD PTR c2$3[rsp], ax
; Line 94
	movzx	eax, WORD PTR c1$2[rsp]
	movzx	ecx, WORD PTR c2$3[rsp]
	cmp	eax, ecx
	je	SHORT $LN8@get_module
; Line 95
	jmp	SHORT $LN5@get_module
$LN8@get_module:
; Line 96
	jmp	$LN4@get_module
$LN5@get_module:
; Line 97
	mov	rax, QWORD PTR module_name$[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	test	eax, eax
	jne	SHORT $LN9@get_module
	mov	rax, QWORD PTR curr_name$4[rsp]
	mov	rcx, QWORD PTR i$1[rsp]
	movzx	eax, WORD PTR [rax+rcx*2]
	test	eax, eax
	jne	SHORT $LN9@get_module
; Line 100
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax+48]
	jmp	SHORT $LN1@get_module
$LN9@get_module:
; Line 103
	mov	rax, QWORD PTR curr_module$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR curr_module$[rsp], rax
; Line 104
	jmp	$LN15@get_module
$LN3@get_module:
; Line 105
	xor	eax, eax
$LN1@get_module:
; Line 106
	add	rsp, 104				; 00000068H
	pop	rdi
	pop	rsi
	ret	0
?get_module_by_name@@YAPEAXPEA_W@Z ENDP			; get_module_by_name
_TEXT	ENDS
END
